CREATE DATABASE IF NOT EXISTS music_db;
USE music_db;
CREATE TABLE songs (
id INT UNSIGNED NOT NULL AUTO_INCREMENT,
artist VARCHAR(50) NOT NULL,
song_title VARCHAR(50) NOT NULL,
release_date INT,
genre VARCHAR(50) NOT NULL,
PRIMARY KEY (id)
);
